### ISSUE TITLE
[doc] deploy documentation on GitHub pages

### ISSUE THREAD

**Issue by jmkerloch** [IGNF/pgrouting-procedures#4]
Documentation should be available on GitHub pages:

- [x] add GitHub action workflow to generate documentation
- [x] step1 : generate documentation with sphinx (waiting #3 )
- [x] step2 : deploy generated documentation on GitHub pages

**Comment by gwenandres** [comment]
Documentation available on https://ignf.github.io/pgrouting-procedures/
