### ISSUE TITLE
[ci] add GitHub action workflow for docker image publication

### ISSUE THREAD

**Issue by jmkerloch** [IGNF/pgrouting-procedures#6]
Create a new `.github/workflows/docker-publish.yml `to add docker publication to CI.

Use https://github.com/marketplace/actions/build-and-push-docker-images to build and push docker image

- [ ] define dockerhub user that will be used for the publication
- [ ] add secrets in GitHub settings to store docker hub user and password
- [ ] use docker GitHub Actions to build and push

**Comment by gwenandres** [comment]
Publication should be done on GitHub Container Registry (ghcr.io)
